name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Ruby ${{ matrix.ruby }}

    strategy:
      fail-fast: true
      matrix:
        ruby:
          - "2.3.0"
          - "2.6.2"
          - "3.0.0"
          - "head"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependent libraries
        run: sudo apt-get install libpq-dev

      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1.61.1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # 'bundle install' and cache

      - name: Check code style
        run: bundle exec rubocop
        continue-on-error: false

      - name: Run tests
        run: bundle exec rake --trace
        continue-on-error: false
